# Configuration file for testing on travis-ci.org
language: python

python:
  - 2.7
  - 3.6
  - 3.7

install:
  - pip install novas_de405
  - python setup.py install

script:
  - python -m unittest discover novas
